server:
  port: 8099

spring:
  application:
    name: monitor
  datasource:
    url: jdbc:postgresql://localhost:5432/monitor_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:DbMigrations
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
